# serverless.yml
service: serverless-service
provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-2
functions:
  query:
    handler: handler.query
    events:
      - http:
          path: serverless
          method: get